# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6022d6500bc2ad0eb80743b2ef85036719814aac34def167c4ab8546dd4a9d9d6f5d42a2999158394496733d36c40f7f22275be4a7835218b5ed654257f090e4

test:
  secret_key_base: f355bfbd5fc0225b8a3fd4533591c7b4a72be61d01e6b24aa46dd329a6d7f1291253ae1c41aca9f8f328d3e0ca75e33386de8d77b8328a105076dc81d791a049

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
