# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15af22c6f0eb7805488b5f91bfe4ff5e8bc4deda208d180a6084daaa7ccccb8b75e16df081addc78d2be6e218a77ebb37a815be61d2cef584dfb8ccc4477aa06

test:
  secret_key_base: e4fdede8efc0fee4ed6c550b94d37dac0f5cb9bed7e0ab6ad5983fe69b230c551a90c1a8188fdaa077fac6bac460f50cef471aacd318e5e12e04e488ee5465e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
